## 감염병전담병원 위치정보수집

In [1]:
import pandas as pd

import requests
from kaggle_secrets import UserSecretsClient
api_key = UserSecretsClient().get_secret('google_api_key')

import pprint

In [2]:
# [첨부파일 참고] 감염병전담병원 지정 현황 (‘20.3.13일 기준) : http://www.mohw.go.kr/react/al/sal0301vw.jsp?PAR_MENU_ID=04&MENU_ID=0403&page=1&CONT_SEQ=353539
str_raw = """합계 67
서울 5 국립중앙의료원, 서울의료원, 서남병원, 서북병원, 보라매병원
부산 1 부산의료원
대구 7
대구의료원, 계명대 대구 동산병원(중구), 근로복지공단
대구병원, 대구보훈병원, 영남대병원, 대구가톨릭대병원,
계명대동산병원(달서구)
인천 5
인천의료원, 인하대학교병원, 길병원, 인천적십자병원,
백령병원
광주 2 빛고을전남대병원, 제2시립요양병원
대전 4
국군대전병원, 시립제2노인전문병원, 충남대병원,
대전보훈병원
울산 5
울산대학교병원, 동강병원, 울산시립노인병원, 중앙병원,
울산병원
세종 1 NK세종병원
경기 7
수원병원, 안성병원, 이천병원, 파주병원, 의정부병원,
포천병원, 성남시의료원
강원 5 원주의료원, 강릉의료원, 속초의료원, 삼척의료원, 영월의료원
충북 2 청주의료원, 충주의료원
충남 4 천안의료원, 공주의료원, 서산의료원, 홍성의료원
전북 3 군산의료원, 남원의료원, 진안군의료원
전남 3 목포시의료원, 순천의료원, 강진의료원
경북 6
포항의료원, 김천의료원, 안동의료원, 상주적십자병원,
영주적십자병원, 국군대구병원(경산)
경남 4
마산의료원, 국립마산병원, 근로복지공단 창원병원,
통영적십자병원
제주 3 제주의료원, 서귀포의료원, 제주대병원"""

hospitals = str_raw.replace(',','').replace('강원','').split()
hospitals = [item for item in hospitals if item[-1] in ('원', ')')]
print('>>> 20.3.13 기준 전국 감염병 전담 병원 수 :', len(hospitals))
print('>>> 20.3.13 기준 전국 감염병 전담 병원 목록 :', hospitals)

>>> 20.3.13 기준 전국 감염병 전담 병원 수 : 67
>>> 20.3.13 기준 전국 감염병 전담 병원 목록 : ['국립중앙의료원', '서울의료원', '서남병원', '서북병원', '보라매병원', '부산의료원', '대구의료원', '동산병원(중구)', '대구병원', '대구보훈병원', '영남대병원', '대구가톨릭대병원', '계명대동산병원(달서구)', '인천의료원', '인하대학교병원', '길병원', '인천적십자병원', '백령병원', '빛고을전남대병원', '제2시립요양병원', '국군대전병원', '시립제2노인전문병원', '충남대병원', '대전보훈병원', '울산대학교병원', '동강병원', '울산시립노인병원', '중앙병원', '울산병원', 'NK세종병원', '수원병원', '안성병원', '이천병원', '파주병원', '의정부병원', '포천병원', '성남시의료원', '원주의료원', '강릉의료원', '속초의료원', '삼척의료원', '영월의료원', '청주의료원', '충주의료원', '천안의료원', '공주의료원', '서산의료원', '홍성의료원', '군산의료원', '남원의료원', '진안군의료원', '목포시의료원', '순천의료원', '강진의료원', '포항의료원', '김천의료원', '안동의료원', '상주적십자병원', '영주적십자병원', '국군대구병원(경산)', '마산의료원', '국립마산병원', '창원병원', '통영적십자병원', '제주의료원', '서귀포의료원', '제주대병원']

In [3]:
# 지역별 감염병 전담 병원 수
str_list = str_raw.split()
r_dict = {}

for idx, item in enumerate(str_list):
    if item in '0123456789':
        r_dict[ str_list[idx-1] ] = item
print(r_dict)

{'합계': '67', '서울': '5', '부산': '1', '대구': '7', '인천': '5', '광주': '2', '대전': '4', '울산': '5', '세종': '1', '경기': '7', '강원': '5', '충북': '2', '충남': '4', '전북': '3', '전남': '3', '경북': '6', '경남': '4', '제주': '3'}

In [4]:
# 구글 api로 병원 주소 및 위경도 생성
location = hospitals[0]
URL = f'https://maps.googleapis.com/maps/api/geocode/json?address={location}&key={api_key}&language=ko'
response = requests.get(URL)
data = response.json()
data

lat = data['results'][0]['geometry']['location']['lat']
lng = data['results'][0]['geometry']['location']['lng']
addr = data['results'][0]['formatted_address']

print(location, lat, lng, addr)
print()
pprint.pprint(data)

국립중앙의료원 37.5672412 127.0056589 대한민국 서울특별시 중구 광희동 을지로 245

{'results': [{'address_components': [{'long_name': '２４５',
                                      'short_name': '２４５',
                                      'types': ['premise']},
                                     {'long_name': '을지로',
                                      'short_name': '을지로',
                                      'types': ['political',
                                                'sublocality',
                                                'sublocality_level_4']},
                                     {'long_name': '광희동',
                                      'short_name': '광희동',
                                      'types': ['political',
                                                'sublocality',
                                                'sublocality_level_2']},
                                     {'long_name': '중구',
                                      'short_name': '중구',
                                      'types': ['political',
                                                'sublocality',
                                                'sublocality_level_1']},
                                     {'long_name': '서울특별시',
                                      'short_name': '서울특별시',
                                      'types': ['administrative_area_level_1',
                                                'political']},
                                     {'long_name': '대한민국',
                                      'short_name': 'KR',
                                      'types': ['country', 'political']},
                                     {'long_name': '100-196',
                                      'short_name': '100-196',
                                      'types': ['postal_code']}],
              'formatted_address': '대한민국 서울특별시 중구 광희동 을지로 245',
              'geometry': {'location': {'lat': 37.5672412, 'lng': 127.0056589},
                           'location_type': 'ROOFTOP',
                           'viewport': {'northeast': {'lat': 37.5685901802915,
                                                      'lng': 127.0070078802915},
                                        'southwest': {'lat': 37.5658922197085,
                                                      'lng': 127.0043099197085}}},
              'place_id': 'ChIJTXe-8CKjfDURI-VwJs68aAM',
              'plus_code': {'compound_code': 'H284+V7 대한민국 서울특별시',
                            'global_code': '8Q99H284+V7'},
              'types': ['establishment',
                        'health',
                        'hospital',
                        'point_of_interest']},
             {'address_components': [{'long_name': '２４５',
                                      'short_name': '２４５',
                                      'types': ['premise']},
                                     {'long_name': '을지로',
                                      'short_name': '을지로',
                                      'types': ['political',
                                                'sublocality',
                                                'sublocality_level_4']},
                                     {'long_name': '광희동',
                                      'short_name': '광희동',
                                      'types': ['political',
                                                'sublocality',
                                                'sublocality_level_2']},
                                     {'long_name': '중구',
                                      'short_name': '중구',
                                      'types': ['political',
                                                'sublocality',
                                                'sublocality_level_1']},
                                     {'long_name': '서울특별시',
                                      'short_name': '서울특별시',
                                      'types': ['administrative_area_level_1',
                                                'political']},
                                     {'long_name': '대한민국',
                                      'short_name': 'KR',
                                      'types': ['country', 'political']},
                                     {'long_name': '100-196',
                                      'short_name': '100-196',
                                      'types': ['postal_code']}],
              'formatted_address': '대한민국 서울특별시 중구 광희동 을지로 245',
              'geometry': {'location': {'lat': 37.568091, 'lng': 127.0056444},
                           'location_type': 'ROOFTOP',
                           'viewport': {'northeast': {'lat': 37.56943998029149,
                                                      'lng': 127.0069933802915},
                                        'southwest': {'lat': 37.56674201970849,
                                                      'lng': 127.0042954197085}}},
              'place_id': 'ChIJM40RAyOjfDURgILILldr7ro',
              'plus_code': {'compound_code': 'H294+67 대한민국 서울특별시',
                            'global_code': '8Q99H294+67'},
              'types': ['establishment', 'funeral_home', 'point_of_interest']}],
 'status': 'OK'}

In [5]:
province_tag_list = []
for key in r_dict.keys():
    if key == '합계':
        continue
    province_tag_list.extend( [key] * eval(r_dict[key]) )
    pass
print(len(province_tag_list))
print(province_tag_list)

67
['서울', '서울', '서울', '서울', '서울', '부산', '대구', '대구', '대구', '대구', '대구', '대구', '대구', '인천', '인천', '인천', '인천', '인천', '광주', '광주', '대전', '대전', '대전', '대전', '울산', '울산', '울산', '울산', '울산', '세종', '경기', '경기', '경기', '경기', '경기', '경기', '경기', '강원', '강원', '강원', '강원', '강원', '충북', '충북', '충남', '충남', '충남', '충남', '전북', '전북', '전북', '전남', '전남', '전남', '경북', '경북', '경북', '경북', '경북', '경북', '경남', '경남', '경남', '경남', '제주', '제주', '제주']

In [6]:
# 구글 api로 병원별 주소 및 위경도 수집
lat_list = []
lng_list = []
addr_list = []
for idx, tmp_location in enumerate(hospitals):
    tmp_location = province_tag_list[idx] + ' ' + tmp_location
    
    URL = f'https://maps.googleapis.com/maps/api/geocode/json?address={tmp_location}&key={api_key}&language=ko'
    response = requests.get(URL)
    data = response.json()
    
    if data['status'] == 'ZERO_RESULTS':
        print(f'>>> Error : No result for {tmp_location} (index : {idx})')
        continue
    
    tmp_lat = data['results'][0]['geometry']['location']['lat']
    tmp_lng = data['results'][0]['geometry']['location']['lng']
    tmp_addr = data['results'][0]['formatted_address']
    
    lat_list.append(tmp_lat)
    lng_list.append(tmp_lng)
    addr_list.append(tmp_addr)
    pass

print('>>> Finished\n')
print(hospitals[-1], lat_list[-1], lng_list[-1], addr_list[-1])

>>> Error : No result for 세종 NK세종병원 (index : 29)
>>> Finished

제주대병원 33.4670429 126.5457559 대한민국 제주특별자치도 제주시 아라동 아란13길 15

In [7]:
# 결측 데이터 추가
tmp_location = '충청남도 연기군 남면 나성리 566'
URL = f'https://maps.googleapis.com/maps/api/geocode/json?address={tmp_location}&key={api_key}&language=ko'
response = requests.get(URL)
data = response.json()

tmp_lat = data['results'][0]['geometry']['location']['lat']
tmp_lng = data['results'][0]['geometry']['location']['lng']
tmp_addr = data['results'][0]['formatted_address']

lat_list.insert(29, tmp_lat)
lng_list.insert(29, tmp_lng)
addr_list.insert(29, tmp_addr)

In [8]:
# 병원별 주소 및 위경도 데이터프레임 생성 및 저장
hospital_df = pd.DataFrame({'name':hospitals, 'lat':lat_list, 'lng':lng_list, 'address':addr_list})
hospital_df.to_csv('감염병전담병원_위치정보.csv', encoding='cp949')

hospital_df.loc[25:30]

        name        lat         lng                            address
25      동강병원  35.553459  129.302082          대한민국 울산광역시 중구 태화동 태화로 239
26  울산시립노인병원  35.421828  129.298104       대한민국 울산광역시 울주군 온양읍 동상리 산86-1
27      중앙병원  35.531573  129.305221          대한민국 울산광역시 남구 신정2동 1651-9
28      울산병원  35.546233  129.323109     대한민국 울산광역시 남구 신정5동 월평로171번길 13
29    NK세종병원  36.479452  127.262336           대한민국 충청남도 연기군 남면 나성리 566
30      수원병원  37.291819  126.996309  대한민국 경기도 수원시 장안구 정자2동 수성로245번길 69

## Region.csv의 지역명 한글화

In [9]:
import pandas as pd

import requests
from kaggle_secrets import UserSecretsClient
api_key = UserSecretsClient().get_secret('google_api_key')

In [10]:
# 지역정보 데이터 로드
region_df = pd.read_csv('../input/coronavirusdataset/Region.csv')
region_df['addr'] = region_df.apply(lambda row : row['province'] + ' ' + row['city'] if row['province'] != row['city'] else row['province'], axis=1)
region_df

,code,province,city,latitude,longitude,elementary_school_count,kindergarten_count,university_count,academy_ratio,elderly_population_ratio,elderly_alone_ratio,nursing_home_count,addr
0,10000,Seoul,Seoul,37.566953,126.977977,607,830,48,1.44,15.38,5.8,22739,Seoul
1,10010,Seoul,Gangnam-gu,37.518421,127.047222,33,38,0,4.18,13.17,4.3,3088,Seoul Gangnam-gu
2,10020,Seoul,Gangdong-gu,37.530492,127.123837,27,32,0,1.54,14.55,5.4,1023,Seoul Gangdong-gu
3,10030,Seoul,Gangbuk-gu,37.639938,127.025508,14,21,0,0.67,19.49,8.5,628,Seoul Gangbuk-gu
4,10040,Seoul,Gangseo-gu,37.551166,126.849506,36,56,1,1.17,14.39,5.7,1080,Seoul Gangseo-gu
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,61160,Gyeongsangnam-do,Haman-gun,35.272481,128.406540,16,20,0,1.19,23.74,14.7,94,Gyeongsangnam-do Haman-gun
240,61170,Gyeongsangnam-do,Hamyang-gun,35.520541,127.725177,13,12,0,1.01,32.65,20.9,83,Gyeongsangnam-do Hamyang-gun
241,61180,Gyeongsangnam-do,Hapcheon-gun,35.566702,128.165870,17,15,0,0.71,38.44,24.7,96,Gyeongsangnam-do Hapcheon-gun
242,70000,Jeju-do,Jeju-do,33.488936,126.500423,113,123,4,1.53,15.10,6.4,1245,Jeju-do
243,80000,Korea,Korea,37.566953,126.977977,6087,8837,340,1.56,15.67,7.2,94865,Korea

In [11]:
# 구글 api로 한글 지역명 및 위경도 수집
lat_list = []
lng_list = []
addr_list = []
for idx, tmp_location in enumerate(region_df.addr):
    URL = f'https://maps.googleapis.com/maps/api/geocode/json?address={tmp_location}&key={api_key}&language=ko'
    response = requests.get(URL)
    data = response.json()
    
    if data['status'] == 'ZERO_RESULTS':
        print(f'>>> Error : No result for {tmp_location} (index : {idx})')
        continue
    
    tmp_lat = data['results'][0]['geometry']['location']['lat']
    tmp_lng = data['results'][0]['geometry']['location']['lng']
    tmp_addr = data['results'][0]['formatted_address']
    
    lat_list.append(tmp_lat)
    lng_list.append(tmp_lng)
    addr_list.append(tmp_addr)
    pass

print('>>> Finished\n')

# 마지막 데이터 확인
print(tmp_location, lat_list[-1], lng_list[-1], addr_list[-1])

>>> Finished

Korea 35.907757 127.766922 대한민국

In [12]:
# 데이터프레임에 수집된 데이터 추가
region_df['google_addr_kor'] = addr_list
region_df['google_lat'] = lat_list
region_df['google_lng'] = lng_list

region_df

,code,province,city,latitude,longitude,elementary_school_count,kindergarten_count,university_count,academy_ratio,elderly_population_ratio,elderly_alone_ratio,nursing_home_count,addr,google_addr_kor,google_lat,google_lng
0,10000,Seoul,Seoul,37.566953,126.977977,607,830,48,1.44,15.38,5.8,22739,Seoul,대한민국 서울특별시,37.566535,126.977969
1,10010,Seoul,Gangnam-gu,37.518421,127.047222,33,38,0,4.18,13.17,4.3,3088,Seoul Gangnam-gu,대한민국 서울특별시 강남구,37.517236,127.047325
2,10020,Seoul,Gangdong-gu,37.530492,127.123837,27,32,0,1.54,14.55,5.4,1023,Seoul Gangdong-gu,대한민국 서울특별시 강동구,37.530125,127.123762
3,10030,Seoul,Gangbuk-gu,37.639938,127.025508,14,21,0,0.67,19.49,8.5,628,Seoul Gangbuk-gu,대한민국 서울특별시 강북구,37.639610,127.025657
4,10040,Seoul,Gangseo-gu,37.551166,126.849506,36,56,1,1.17,14.39,5.7,1080,Seoul Gangseo-gu,대한민국 서울특별시 강서구,37.550979,126.849538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,61160,Gyeongsangnam-do,Haman-gun,35.272481,128.406540,16,20,0,1.19,23.74,14.7,94,Gyeongsangnam-do Haman-gun,대한민국 경상남도 함안군,35.272559,128.406480
240,61170,Gyeongsangnam-do,Hamyang-gun,35.520541,127.725177,13,12,0,1.01,32.65,20.9,83,Gyeongsangnam-do Hamyang-gun,대한민국 경상남도 함양군,35.520461,127.725176
241,61180,Gyeongsangnam-do,Hapcheon-gun,35.566702,128.165870,17,15,0,0.71,38.44,24.7,96,Gyeongsangnam-do Hapcheon-gun,대한민국 경상남도 합천군,35.566576,128.165799
242,70000,Jeju-do,Jeju-do,33.488936,126.500423,113,123,4,1.53,15.10,6.4,1245,Jeju-do,대한민국 제주특별자치도,33.489011,126.498302
243,80000,Korea,Korea,37.566953,126.977977,6087,8837,340,1.56,15.67,7.2,94865,Korea,대한민국,35.907757,127.766922

In [13]:
# 이상치 확인
display(region_df[ (region_df.google_addr_kor.str[:4]!='대한민국') | (region_df.google_addr_kor.str.len()>15) ])

# 이상치 수정(세종시, 창원시, 한국)
region_df.loc[81, 'google_addr_kor'] = '대한민국 세종특별자치시'
region_df.loc[236, 'google_addr_kor'] = '대한민국 경상남도 창원시'
region_df.loc[243, 'google_addr_kor'] = '대한민국'

# 이상치 없어진 것 확인
display(region_df[ (region_df.google_addr_kor.str[:4]!='대한민국') | (region_df.google_addr_kor.str.len()>15) ])

,code,province,city,latitude,longitude,elementary_school_count,kindergarten_count,university_count,academy_ratio,elderly_population_ratio,elderly_alone_ratio,nursing_home_count,addr,google_addr_kor,google_lat,google_lng
81,17000,Sejong,Sejong,36.480132,127.289021,48,60,3,1.78,9.48,3.8,491,Sejong,"1330 Blair Ave, St Paul, MN 55104 미국",44.961021,-93.156633
236,61130,Gyeongsangnam-do,Changwon-si,35.227992,128.681815,110,195,5,1.84,13.64,6.5,1701,Gyeongsangnam-do Changwon-si,"대한민국 경상남도 Changwon, 창원시 의창구 두대동 원이대로 332",35.239204,128.655330

Empty DataFrame
Columns: [code, province, city, latitude, longitude, elementary_school_count, kindergarten_count, university_count, academy_ratio, elderly_population_ratio, elderly_alone_ratio, nursing_home_count, addr, google_addr_kor, google_lat, google_lng]
Index: []

In [14]:
# 시/도 한글명, 시/군/구 한글명 분리 저장
region_df['google_addr_kor'] = region_df['google_addr_kor'].str.replace('대한민국 ', '')
region_df['province_kor'] = region_df['google_addr_kor'].map(lambda x : x.split()[0])
region_df['city_kor'] = region_df['google_addr_kor'].map(lambda x : x.split()[0] if len(x.split())==1 else x.split()[1])

# 불필요 컬럼 제거 후 저장 및 확인
region_df = region_df.drop(columns=['addr', 'google_addr_kor'])
region_df.to_csv('Region_translated.csv', index=False)
region_df

,code,province,city,latitude,longitude,elementary_school_count,kindergarten_count,university_count,academy_ratio,elderly_population_ratio,elderly_alone_ratio,nursing_home_count,google_lat,google_lng,province_kor,city_kor
0,10000,Seoul,Seoul,37.566953,126.977977,607,830,48,1.44,15.38,5.8,22739,37.566535,126.977969,서울특별시,서울특별시
1,10010,Seoul,Gangnam-gu,37.518421,127.047222,33,38,0,4.18,13.17,4.3,3088,37.517236,127.047325,서울특별시,강남구
2,10020,Seoul,Gangdong-gu,37.530492,127.123837,27,32,0,1.54,14.55,5.4,1023,37.530125,127.123762,서울특별시,강동구
3,10030,Seoul,Gangbuk-gu,37.639938,127.025508,14,21,0,0.67,19.49,8.5,628,37.639610,127.025657,서울특별시,강북구
4,10040,Seoul,Gangseo-gu,37.551166,126.849506,36,56,1,1.17,14.39,5.7,1080,37.550979,126.849538,서울특별시,강서구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,61160,Gyeongsangnam-do,Haman-gun,35.272481,128.406540,16,20,0,1.19,23.74,14.7,94,35.272559,128.406480,경상남도,함안군
240,61170,Gyeongsangnam-do,Hamyang-gun,35.520541,127.725177,13,12,0,1.01,32.65,20.9,83,35.520461,127.725176,경상남도,함양군
241,61180,Gyeongsangnam-do,Hapcheon-gun,35.566702,128.165870,17,15,0,0.71,38.44,24.7,96,35.566576,128.165799,경상남도,합천군
242,70000,Jeju-do,Jeju-do,33.488936,126.500423,113,123,4,1.53,15.10,6.4,1245,33.489011,126.498302,제주특별자치도,제주특별자치도
243,80000,Korea,Korea,37.566953,126.977977,6087,8837,340,1.56,15.67,7.2,94865,35.907757,127.766922,대한민국,대한민국

## Region.csv의 일부 지역명 갱신

In [15]:
import pandas as pd

region_df = pd.read_csv('../input/coronavirusdatasetmodified/Region_translated.csv')
region_df.loc[region_df.city_kor == '여주군', 'city_kor'] = '여주시'
region_df.loc[(region_df.province_kor == '인천광역시')&(region_df.city_kor == '남구'), 'city_kor'] = '미추홀구'

display(region_df[(region_df.city_kor == '여주시') | (region_df.city_kor == '미추홀구')])
region_df.to_csv('Region_translated.csv', index=False)

,code,province,city,latitude,longitude,elementary_school_count,kindergarten_count,university_count,academy_ratio,elderly_population_ratio,elderly_alone_ratio,nursing_home_count,google_lat,google_lng,province_kor,city_kor
61,14030,Incheon,Michuhol-gu,37.463572,126.650270,29,43,2,0.9,16.29,6.8,643,37.463681,126.650477,인천광역시,미추홀구
102,20200,Gyeonggi-do,Yeoju-si,37.298209,127.637351,23,34,1,1.0,21.05,8.8,191,37.298024,127.637163,경기도,여주시